name: Build/Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Initialize Environment
        uses: actions/setup-node@v1
        with:
          node-version: 16.8.0

      - name: Install Dependencies
        run: yarn

      - name: Deploy
        run: yarn deploy